{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1dcd3b79-72ae-4866-ad78-8d90bf2c43b3",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'playground.analysis.dataset'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 7\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;66;03m# 0.Setting\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[38;5;66;03m# Section A. View Point\u001b[39;00m\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mjoonmyung\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdraw\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m drawImgPlot\n\u001b[0;32m----> 7\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mplayground\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01manalysis\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdataset\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m JDataset\n\u001b[1;32m      8\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mplayground\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01manalysis\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodel\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m JModel\n\u001b[1;32m     10\u001b[0m view \u001b[38;5;241m=\u001b[39m [\u001b[38;5;28;01mTrue\u001b[39;00m, \u001b[38;5;28;01mFalse\u001b[39;00m, \u001b[38;5;28;01mFalse\u001b[39;00m, \u001b[38;5;28;01mTrue\u001b[39;00m, \u001b[38;5;28;01mTrue\u001b[39;00m] \u001b[38;5;66;03m# [Image, Attention, Rollout, GradCam, What I Want]\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'playground.analysis.dataset'"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import os\n",
    "\n",
    "# 0.Setting\n",
    "# Section A. View Point\n",
    "from joonmyung.draw import drawImgPlot\n",
    "from playground.analysis.dataset import JDataset\n",
    "from playground.analysis.model import JModel\n",
    "\n",
    "view = [True, False, False, True, True] # [Image, Attention, Rollout, GradCam, What I Want]\n",
    "save_path, save = '/hub_data/joonmyung/conference/playgrounds/results/', False\n",
    "\n",
    "# Section B. Data\n",
    "root_path, dataset = \"/hub_data/joonmyung/data\", \"imagenet\"\n",
    "data_num = [[0, 0], [1, 0], [2, 0], [3, 0], [0, 1], [1, 1], [2, 1], [3, 1]]\n",
    "B = len(data_num)\n",
    "lam = 0.6\n",
    "num_classes = 1000 if dataset == \"imagenet\" else 100\n",
    "\n",
    "# Section C. Condition\n",
    "es = []\n",
    "# ls = [0, 2, 4, 6]\n",
    "les = [-3, -1]\n",
    "query_num = 15\n",
    "columns = 4\n",
    "\n",
    "# Section D. HeatMap Condition\n",
    "fmt, border, cbar    = 0, True, False\n",
    "\n",
    "# model_name = \"PATCH\"\n",
    "device_type = 'cuda'\n",
    "device = torch.device(device_type)\n",
    "\n",
    "# 2. Load Data\n",
    "dataset = JDataset(root_path, dataset, device)\n",
    "samples, targets, imgs, label_names = dataset.getitems(data_num)\n",
    "label_names.insert(0, f\"{label_names[0]} : {lam} + {label_names[1]} : {1 - lam}\")\n",
    "label_names.insert(0, f\"{label_names[0]} : {1-lam} + {label_names[1]} : {lam}\")\n",
    "if view[0]:\n",
    "    drawImgPlot(dataset.unNormalize(samples), columns = label_names, col=len(samples))\n",
    "\n",
    "\n",
    "model_name, model_path = \"DEIT\", \"/hub_data/joonmyung/conference/2023ICCV/1.3.2/OURS:T:01/checkpoint_{}.pth\"\n",
    "model_number, ana_type, epoch = 1, \"2023ICCV\", 0\n",
    "\n",
    "print(\"file list : \", os.listdir(\"/\" + os.path.join(*model_path.split(\"/\")[:-1])))\n",
    "\n",
    "modelMaker = JModel(model_name, num_classes, model_path, model_number=model_number, ana_type = ana_type, device=device)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0a6fa22e-89ac-4431-be7f-eec88e57ab53",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-236239e14297>\", line 5, in <module>\n",
      "    outputs, output_12, loss_mask, loss_mae_1, loss_mae_2, mask_acc, mae_target, mae_target_mixed, mae_pred_1, mae_pred_2, indices, lam = model(samples)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 889, in _call_impl\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/joonmyung/project/JoonMyung/playground/analysis/models/mae_trans/deit.py\", line 414, in forward\n",
      "    cls_token, loss_mask, loss_mae_1, loss_mae_2, mask_acc, mae_target, mae_pred_1, mae_pred_2 = self.forward_loss(imgs, pred, mask_a, mask, attn, cls_token, indices)\n",
      "  File \"/home/joonmyung/project/JoonMyung/playground/analysis/models/mae_trans/deit.py\", line 363, in forward_loss\n",
      "    ab_match = ((1 - mask_1 ^ mask_pred_a).sum(dim=[1, 2]) > (self.num_patches // 2)).type(torch.int64).reshape(-1, 1, 1) # (128, 1, 1)\n",
      "TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-236239e14297>\", line 5, in <module>\n",
      "    outputs, output_12, loss_mask, loss_mae_1, loss_mae_2, mask_acc, mae_target, mae_target_mixed, mae_pred_1, mae_pred_2, indices, lam = model(samples)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 889, in _call_impl\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/joonmyung/project/JoonMyung/playground/analysis/models/mae_trans/deit.py\", line 414, in forward\n",
      "    cls_token, loss_mask, loss_mae_1, loss_mae_2, mask_acc, mae_target, mae_pred_1, mae_pred_2 = self.forward_loss(imgs, pred, mask_a, mask, attn, cls_token, indices)\n",
      "  File \"/home/joonmyung/project/JoonMyung/playground/analysis/models/mae_trans/deit.py\", line 363, in forward_loss\n",
      "    ab_match = ((1 - mask_1 ^ mask_pred_a).sum(dim=[1, 2]) > (self.num_patches // 2)).type(torch.int64).reshape(-1, 1, 1) # (128, 1, 1)\n",
      "TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-236239e14297>\", line 5, in <module>\n",
      "    outputs, output_12, loss_mask, loss_mae_1, loss_mae_2, mask_acc, mae_target, mae_target_mixed, mae_pred_1, mae_pred_2, indices, lam = model(samples)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 889, in _call_impl\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/joonmyung/project/JoonMyung/playground/analysis/models/mae_trans/deit.py\", line 414, in forward\n",
      "    cls_token, loss_mask, loss_mae_1, loss_mae_2, mask_acc, mae_target, mae_pred_1, mae_pred_2 = self.forward_loss(imgs, pred, mask_a, mask, attn, cls_token, indices)\n",
      "  File \"/home/joonmyung/project/JoonMyung/playground/analysis/models/mae_trans/deit.py\", line 363, in forward_loss\n",
      "    ab_match = ((1 - mask_1 ^ mask_pred_a).sum(dim=[1, 2]) > (self.num_patches // 2)).type(torch.int64).reshape(-1, 1, 1) # (128, 1, 1)\n",
      "TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/home/joonmyung/.conda/envs/2023ICCV_MIXUP/lib/python3.6/posixpath.py\", line 383, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    }
   ],
   "source": [
    "es = [0, 20,40, 60, 80, 100, 120]\n",
    "for e in es:\n",
    "    model = modelMaker.getModel(e)[0]\n",
    "    model.eval()\n",
    "    outputs, output_12, loss_mask, loss_mae_1, loss_mae_2, mask_acc, mae_target, mae_target_mixed, mae_pred_1, mae_pred_2, indices, lam = model(samples)\n",
    "    drawImgPlot(torch.stack([mae_target, mae_target_mixed, mae_target[indices], mae_pred_1, mae_pred_2], dim=1).reshape(-1, 3, 224, 224)[5:10], col=5);"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ffd342e-64dd-4d25-b7f5-753ca1c7e8d0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bc9bb5f2-cf39-4ec2-b730-4f0a393f7084",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "414b8221-795a-4a98-8722-b54834417962",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "joonmyung",
   "language": "python",
   "name": "joonmyung"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
